### CREATE
POST http://localhost:3333/document
Content-type: application/json

{
    "action": "create",
    "key": "nome",
    "value": "João"
}

###

POST http://localhost:3333/document
Content-Type: application/json

{
    "action": "create",
    "key": "idade",
    "value": "17"
}
###

### UPDATE

POST http://localhost:3333/document
Content-Type: application/json

{
    "action": "update",
    "key": "nome",
    "value": "João"
}

###

### LIST
GET http://localhost:3333/document

### DELETE